### ISSUE TITLE
Unable to save or load offline data

### ISSUE THREAD

**Issue by stevekm** [schneefux/python-gamelocker#8]
I have been looking for ways to save data retrieved with `gamelocker` but have been unsuccessful. For example, `pickle` returns an error when trying to save matches:

```
import pickle
import gamelocker

api = gamelocker.Gamelocker(key).Vainglory()
matches = api.matches({"page[limit]": 5})
with open("saved_match.pickle", 'wb') as f:
    pickle.dump(matches, f, pickle.HIGHEST_PROTOCOL)

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
```

I have also been digging through the source code of `gamelocker` trying to find a way to import a saved JSON payload directly from a file, instead of returned from the API, but have not been able to find a way yet. 

Is this supported?

**Comment by schneefux** [comment]
I did not have this use case in mind when I built the wrapper. You have the following options…

*  It is best if you develop a custom storage format and store it for example in an SQLite database, or you could write your own serializer.
* You can set up a http proxy that caches the API responses and override `api._apiurl` to point to localhost.
* You can parse a stored JSON file by using the parser in gamelocker.datatypes, as seen here https://github.com/schneefux/python-gamelocker/blob/174019005c5dbb3b77d7a9db7e51c633fa7cbf71/gamelocker/api.py#L77. You would read `data` from a file instead of doing a http request, but the rest of the code is the same.

**Comment by stevekm** [comment]
Thanks, parsing JSON seems the easiest. Will try it out & let you know if I can't figure it out. The lack of offline saving/loading has been a bit of a headache when I am trying to work on building my app but don't have Internet access.
